### ISSUE TITLE
Need ConfigBuilder methods to add custom converters

### ISSUE THREAD

**Issue by tevans78** [Emily-Jiang/microprofile.config.incubator#12]
e.g. ConfigBuilder.addConverter(Converter<T>)

**Comment by Emily-Jiang** [comment]
added a /**
      \* Add a converter {@link Converter} to the builder
      \* @param converter the converter
      \* @param convererTyper the class type that the converter is supposed to convert from a string 
      \* @return the builder
      */
     <T> ConfigBuilder addConverter(Converter<T> converter, Class<?> converterType);

**Comment by tevans78** [comment]
Converter should be parameterized...
ConfigBuilder <T> addConverter(Converter<T> converter. Class<T> converterType)

**Comment by tevans78** [comment]
Turns out that can't re-open issues :-(
