### ISSUE TITLE
What do you do if multiple ConfigSources report the same ordinal

### ISSUE THREAD

**Issue by tevans78** [Emily-Jiang/microprofile.config.incubator#15]
Undefined??

**Comment by tevans78** [comment]
Perhaps the ordinal on the ConfigSource is just a default or base value and the actual value should be unique depending on the order the sources were added?

If you have two sources with a "base" ordinal of 400, should only the first one actually get 400; should the second one resolve to 401 (i.e. higher and more important because it was added more recently)?

**Comment by Emily-Jiang** [comment]
It is legal for multiple sources to have the same ordinal, which means the properties defined in these config sources have the same priority. If the same property is defined in multiple sources with the same ordinal, the property value could be from any of them. Undefined behaviour.
