### ISSUE TITLE
ConfigBuilder is missing a way to add custom Converters

### ISSUE THREAD

**Issue by tevans78** [Emily-Jiang/microprofile.config.incubator#20]
Need methods such as addConverter and withConverters
Might also want a way of listing existing ones or getting the one for a particular type

**Comment by Emily-Jiang** [comment]
added /**
      \* Add a converter {@link Converter} to the builder
      \* @param converter the converter
      \* @param convererTyper the class type that the converter is supposed to convert from a string 
      \* @return the builder
      */
     <T> ConfigBuilder addConverter(Converter<T> converter, Class<?> converterType);
