### ISSUE TITLE
Need a method on ConfigBuilder to list the ConfigSources (edit)

### ISSUE THREAD

**Issue by tevans78** [Emily-Jiang/microprofile.config.incubator#21]
Something like...
public Collection<ConfigSource> getSources()

**Comment by Emily-Jiang** [comment]
added. also added the 
    /**
      \* Return the collection of {@link Converter}s.
      \* @return the collection of {@link Converter}s.
      */
     public Collection<Converter> getConverters();

**Comment by tevans78** [comment]
should be parameterized like for ConfigSources ...
`public Collection<Converter> getConverters()`

**Comment by tevans78** [comment]
Noticed that in these issues the '<>'  chars are special (markdown?) so they don't show up if not formatted as code
