### ISSUE TITLE
Config need generic getObject methods

### ISSUE THREAD

**Issue by tevans78** [Emily-Jiang/microprofile.config.incubator#5]
You need the raw generic form to work with custom converters...
    public <T> T getObject(String key, Class<T> clazz);
    public <T> T getObject(String key, Class<T> clazz, T defaultValue);

**Comment by tevans78** [comment]
Just noticed that there is a getProperty method which is similar ... but no flavour with a default value.

**Comment by Emily-Jiang** [comment]
added the following
/**
     \* Return the resolved property value with the specified type for the specified property name or
     \* defaultValue if the property does not exist.
     \* @param propertyName the property name
     \* @param propertyType the property type
     \* @param defaultValue the default value
     \* @return the property value 
     */
    <T> T getProperty(String propertyName, Class<T> propertyType, T defaultValue);
