### ISSUE TITLE
Config needs methods which allows for null to be returned

### ISSUE THREAD

**Issue by tevans78** [Emily-Jiang/microprofile.config.incubator#7]
e.g. for boolean there is...
    boolean getBoolean(String propertyName);
    boolean getBoolean(String propertyName, boolean defaultValue);
    Boolean getBoolean(String propertyName, Boolean defaultValue);
none of these ever return null if the property does not exist. Need to add
    Boolean getBoolean(String propertyName);

**Comment by Emily-Jiang** [comment]
Updated boolean getBoolean(String propertyName); to Boolean getBoolean(String propertyName);
