### ISSUE TITLE
JavaDoc should make it clear what will happen if a property does not exist

### ISSUE THREAD

**Issue by tevans78** [Emily-Jiang/microprofile.config.incubator#8]
e.g. the simple boolean primitive method ... does it throw IllegalArgumentException if the property does not exist
    /**
     * Get a boolean associated with the given configuration propertyName.
     *
     * @param propertyName The configuration propertyName.
     * @return The associated boolean.
     *
     * @throws IllegalArgumentException is thrown if the propertyName maps to an
     *         object that is not a Boolean.
     */
    boolean getBoolean(String propertyName);

**Comment by Emily-Jiang** [comment]
updated this method to Boolean getBoolean(String propertyName), returns null if the property does not exist.
